database drop Scenario01_DB;
database create Scenario01_DB;
database use Scenario01_DB;
schema Scenario01_Schema { name: string; salary: float; };
drop structure Scenario01_Collection;
create collection Scenario01_Collection based on Scenario01_Schema;
rename database from Scenario01_DB to Scenario01_DB_RENAME;
rename database from Scenario01_DB_RENAME to Scenario01_DB;
rename structure from Scenario01_Collection to Scenario01_Collection_RENAME;
rename structure from Scenario01_Collection_RENAME to Scenario01_Collection;
rename field from Scenario01_Collection::salary to Scenario01_Collection::salary_RENAME;
rename field from Scenario01_Collection::salary_RENAME to Scenario01_Collection::salary;
schema Scenario01_Schema_dummy1 { name: string; };
drop structure Scenario01_Collection_dummy1;
create collection Scenario01_Collection_dummy1 based on Scenario01_Schema_dummy1;
schema Scenario01_Schema_dummy2 { somefield: string; dummy1: dummy1; };
drop structure Scenario01_Collection_dummy2;
create collection Scenario01_Collection_dummy2 based on Scenario01_Schema_dummy2;
rebind Scenario01_Collection_dummy2::dummy1 to Scenario01_Collection_dummy1;
migrate structure Scenario01_Collection_dummy2 to Scenario01_Schema_dummy1 using [ somefield => name ];
insert into Scenario01_Collection objects [ {"name":"Bob","salary":"4000"} {"name":"George","salary":"4500"} {"name":"Akshan","salary":"1000000"} ];
select from structure Scenario01_Collection where ( 1 == 1 ) fields [ salary, name ];
update structure Scenario01_Collection where ( name == Akshan ) modify [ salary => 2000000 ];
select from structure Scenario01_Collection where ( 1 == 1 ) fields [ salary, name ];
truncate structure Scenario01_Collection;
select from structure Scenario01_Collection where ( 1 == 1 ) fields [ salary, name ];
user remove SomeUser;
user create SomeUser password passwd;
user remove SomeUser;
user create SomeUser password passwd;
user create SomeUser password passwd;
grant [ create, update, delete ] to SomeUser on Scenario01_Collection;
Revoke [ create, update, delete ] from SomeUser on Scenario01_Collection;
commit;
savepoint d4b2758da0205c1e0aa9512cd188002a;
rollback d4b2758da0205c1e0aa9512cd188002a;