database drop Scenario02_DB;
database create Scenario02_DB;
database use Scenario02_DB;
schema Scenario02_Schema { name: string; salary: float; };
drop structure Scenario02_Collection;
create collection Scenario02_Collection based on Scenario02_Schema;
rename database from Scenario02_DB to Scenario02_DB_RENAME;
rename database from Scenario02_DB_RENAME to Scenario02_DB;
rename structure from Scenario02_Collection to Scenario02_Collection_RENAME;
rename structure from Scenario02_Collection_RENAME to Scenario02_Collection;
rename field from Scenario02_Collection::salary to Scenario02_Collection::salary_RENAME;
rename field from Scenario02_Collection::salary_RENAME to Scenario02_Collection::salary;
schema Scenario02_Schema_dummy1 { name: string; };
drop structure Scenario02_Collection_dummy1;
create collection Scenario02_Collection_dummy1 based on Scenario02_Schema_dummy1;
schema Scenario02_Schema_dummy2 { somefield: string; dummy1: dummy1; };
drop structure Scenario02_Collection_dummy2;
create collection Scenario02_Collection_dummy2 based on Scenario02_Schema_dummy2;
rebind Scenario02_Collection_dummy2::dummy1 to Scenario02_Collection_dummy1;
migrate structure Scenario02_Collection_dummy2 to Scenario02_Schema_dummy1 using [ somefield => name ];
insert into Scenario02_Collection objects [ {"name":"Bob","salary":"4000"} {"name":"George","salary":"4500"} {"name":"Akshan","salary":"1000000"} ];
select from structure Scenario02_Collection where ( 1 == 1 ) fields [ salary, name ];
update structure Scenario02_Collection where ( name == Akshan ) modify [ salary => 2000000 ];
select from structure Scenario02_Collection where ( 1 == 1 ) fields [ salary, name ];
truncate structure Scenario02_Collection;
select from structure Scenario02_Collection where ( 1 == 1 ) fields [ salary, name ];
user remove SomeUser;
user create SomeUser password passwd;
user remove SomeUser;
user create SomeUser password passwd;
user create SomeUser password passwd;
grant [ create, update, delete ] to SomeUser on Scenario02_Collection;
Revoke [ create, update, delete ] from SomeUser on Scenario02_Collection;
commit;
savepoint d4b2758da0205c1e0aa9512cd188002a;
rollback d4b2758da0205c1e0aa9512cd188002a;
