@startuml Revoke
!theme crt-amber

namespace LunarDB.QueryData {

struct Revoke {
    + permissions : std::vector<Primitives::EUserPermissionType>
    + from_user : std::string
    + structure_name : std::optional<std::string>
}

}

@enduml
