@startuml OrderType


namespace LunarDB.QueryData.Primitives {

namespace OrderType {

enum Literal {
    None,
    Asc,
    Desc
}

stereotype convertor {
    + toString(primitive: Literal) : std::string_view
    + toLiteral(str: std::string_view) : Literal
    + operator<<(os: std::ostream&, rhs: Literal const&) : std::ostream
}

Literal <- convertor : use

}

}
@enduml
