@startuml QueryType
!theme crt-amber

namespace LunarDB.QueryData.Primitives {

namespace QueryType {

enum Literal {
    None,
    Create,
    Drop,
    Migrate,
    Truncate,
    Rename,
    Select,
    Insert,
    Update,
    Delete,
    Grant,
    Revoke,
    Commit,
    Rollback,
    SavePoint,
    Database,
    Rebind,
    Schema
}

stereotype convertor {
    + toString(primitive: Literal) : std::string_view
    + toLiteral(str: std::string_view) : Literal
    + operator<<(os: std::ostream&, rhs: Literal const&) : std::ostream
}

Literal <- convertor : use

}

}
@enduml
