@startuml StructureType
!theme crt-amber

namespace LunarDB.QueryData.Primitives {

namespace StructureType {

enum Literal {
    None,
    Table,
    Collection
}

stereotype convertor {
    + toString(primitive: Literal) : std::string_view
    + toLiteral(str: std::string_view) : Literal
    + operator<<(os: std::ostream&, rhs: Literal const&) : std::ostream
}

Literal <- convertor : use

}

}

@enduml
