#include "QueryData.hpp"

#define PROVIDE_EQUALITY_OPERATOR(Type, ...) \
namespace LunarDB::Moonlight::QueryData { \
bool operator==(const Type& lhs, const Type& rhs) \
{ \
const auto reduce = [](const Type& obj) { return std::tie(__VA_ARGS__); }; \
return reduce(lhs) == reduce(rhs); \
} \
}

PROVIDE_EQUALITY_OPERATOR(Create)
PROVIDE_EQUALITY_OPERATOR(Drop)
PROVIDE_EQUALITY_OPERATOR(Migrate)
PROVIDE_EQUALITY_OPERATOR(Truncate)
PROVIDE_EQUALITY_OPERATOR(Rename)
PROVIDE_EQUALITY_OPERATOR(Select)
PROVIDE_EQUALITY_OPERATOR(Insert)
PROVIDE_EQUALITY_OPERATOR(Update)
PROVIDE_EQUALITY_OPERATOR(Delete)
PROVIDE_EQUALITY_OPERATOR(Lock)
PROVIDE_EQUALITY_OPERATOR(Grant)
PROVIDE_EQUALITY_OPERATOR(Revoke)
PROVIDE_EQUALITY_OPERATOR(Commit)
PROVIDE_EQUALITY_OPERATOR(Rollback)
PROVIDE_EQUALITY_OPERATOR(SavePoint)
PROVIDE_EQUALITY_OPERATOR(Index)
PROVIDE_EQUALITY_OPERATOR(Database)
PROVIDE_EQUALITY_OPERATOR(View)
